exec config.cfg
//exec threading.cfg

fov_desired "99"
mat_forceaniso "16"
mat_picmip "-10"
mat_trilinear "1"
mat_vsync "1"
mat_forcehardwaresync "1"
mat_parallaxmap	"1"
mat_reducefillrate "0"
r_shadowrendertotexture	"1"
r_rootlod "0"
r_lod "-8"
r_waterforceexpensive "1"
r_waterforcereflectentities	"1"
mat_antialias "1"
mat_aaquality "0"
mat_specular "1"
mat_bumpmap	"1"
mat_hdr_level "3"
mat_colorcorrection	"1"

gib_ragdoll_blast_chance "0.75"
gib_ragdoll_energy_chance "0.075"
cl_ragdoll_bloodpool_chance "5"
sv_generic_gib_max_limit "100"
sv_generic_gib_ideal_count "50"
sv_npc_gib_max_limit "100"
sv_npc_gib_ideal_count "50"
sv_player_gib_max_limit "100"
sv_player_gib_ideal_count "50"
sv_gib_system_allow_vort_fx "1"
cl_generic_gib_max_limit "100"
cl_generic_gib_ideal_count "50"
cl_npc_gib_max_limit "100"
cl_npc_gib_ideal_count "50"
cl_player_gib_max_limit "100"
cl_player_gib_ideal_count "50"
cl_dlight_manager_max_fps "45"
cl_dlight_manager_min_fps "30"
cl_dlight_manager_enable "0"
cl_battery_dlights "1"
cl_generic_gib_remove_per_frame_count "1"
cl_npc_gib_remove_per_frame_count "1"
cl_player_gib_remove_per_frame_count "1"
cl_ragdoll_collide "1"
cl_ragdoll_physics_enable "1"
cl_mdldetailfx_enable "1"
cl_mdldetailfx_enable_hands "1"
cl_weapon_shellbrass_enable "1"

cl_forcepreload "1"
sv_forcepreload "1"
mem_force_flush "0"
mod_forcedata "1"
mod_forcetouchdata "1"
mat_compressedtextures "0"
mat_use_compressed_hdr_textures "1"

cl_blobbyshadows "0"
cl_first_person_uses_world_model "0"
mp_decals "3333"
r_decals "3333"
r_maxmodeldecal "222"
func_break_max_pieces "33"
cl_weapon_shellbrass_life "99"
cl_mdldetailfx_blood_time "99"
cl_mdldetailfx_slime_time  "33"
cl_ragdoll_max "99"
cl_ragdoll_max_generic "111"
cl_ragdoll_max_npc "66"
cl_ragdoll_max_player "44"
g_ragdoll_lvfadespeed "9999"
g_ragdoll_fadespeed "9999"

dsp_enhance_stereo "1"
snd_mixahead "1"
snd_mix_async "1"
mat_queue_mode "2"
//r_queued_decals "1" --Causes crashing
//r_queued_post_processing "1" --Causes crashing
r_queued_ropes "1"
r_threaded_renderables "1"
r_threaded_particles "1"
r_threaded_client_shadow_manager "1"
cl_threaded_bone_setup "1"
cl_threaded_client_leaf_system "1"

datacachesize "512"
mem_min_heapsize "128"
mem_max_heapsize "4096"
mem_max_heapsize_dedicated "1024"

//doubled values
cl_detaildist "2400"
cl_detailfade "800"
lod_transitiondist "1600"
r_maxsampledist "256"
r_maxdlights "64"
r_worldlights "8"
r_shadowmaxrendered "64"
r_maxnewsamples "12"

cl_interp "0"
cl_interp_ratio "1"

cl_impacteffects "1"
cl_burninggibs "1"
cl_new_impact_effects "1"
cl_ejectbrass "1"
cl_show_splashes "1"
cl_ShowSunVectors "1"

mat_filterlightmaps "1"
mat_filtertextures "1"
mat_mipmaptextures "1"
muzzleflash_light "1"
r_ambientboost "1"
r_drawdecals "1"
r_drawflecks "1"
r_eyegloss "1"
r_eyemove "1"
r_drawmodeldecals "1"
r_dynamic "1"
r_occlusion "1"
r_shadows "1"
r_WaterDrawReflection "1"
r_WaterDrawRefraction "1"
sv_robust_explosions "1"
violence_ablood "1"
violence_agibs "1"
violence_hblood "1"
violence_hgibs "1"

echo Autoexec Config Loaded!